import PDFDocument from "pdfkit";
import {
  artifactFilename,
  KILN_DISCLAIMER,
  type ArtifactInput,
  type ArtifactBuffer,
} from "./types";

// Single-page PDF for the deal-desk review meeting. Uses pdfkit's default
// Helvetica family (no font registration needed — keeps the bundle small and
// avoids file-system font-load surprises in serverless).
//
// Layout (US Letter, 1" margins):
//   - Header band: customer name (ALL CAPS small) + deal name (large) + ACV/term
//   - Disclaimer chip on the right
//   - Sections from comms.approval_review_one_pager.sections, rendered as
//     UPPERCASE heading + body
//   - Footer: Generated by Kiln · review URL · generated_at
//
// Single page is enforced — if the agent's content overflows we truncate the
// last section and append "(see full review)". This keeps the artifact
// "scannable in a deal-desk review meeting" per the spec.

const PAGE_OPTS = {
  size: "LETTER",
  margins: { top: 56, bottom: 56, left: 56, right: 56 },
} as const;

const COLORS = {
  brand: "#3B82F6", // Clay blue
  ink: "#0A0A0A",
  muted: "#737373",
  border: "#E5E5E5",
};

export async function generateApprovalOnePager(
  input: ArtifactInput,
): Promise<ArtifactBuffer> {
  const { deal, comms, approval, appUrl } = input;
  const onePager = comms.approval_review_one_pager;

  const doc = new PDFDocument(PAGE_OPTS);
  const chunks: Buffer[] = [];
  doc.on("data", (c: Buffer) => chunks.push(c));
  const closed = new Promise<void>((res) => doc.on("end", () => res()));

  // ---- Header band ----
  doc
    .font("Helvetica-Bold")
    .fontSize(8)
    .fillColor(COLORS.muted)
    .text(deal.customer.name.toUpperCase(), { characterSpacing: 1.5 });
  doc.moveDown(0.2);
  doc
    .font("Helvetica-Bold")
    .fontSize(20)
    .fillColor(COLORS.ink)
    .text(onePager.title || deal.name, { lineBreak: true });
  doc.moveDown(0.2);
  doc
    .font("Helvetica")
    .fontSize(10)
    .fillColor(COLORS.muted)
    .text(metadataLine(input), { continued: false });

  doc.moveDown(0.6);
  rule(doc);
  doc.moveDown(0.6);

  // ---- Sections ----
  const remainingHeightAtStart = remainingHeight(doc);
  const usableSections = trimSectionsToFit(doc, onePager.sections);

  for (const s of usableSections) {
    if (remainingHeight(doc) < 60) break;
    doc
      .font("Helvetica-Bold")
      .fontSize(9)
      .fillColor(COLORS.brand)
      .text(s.heading.toUpperCase(), { characterSpacing: 1.2 });
    doc.moveDown(0.25);
    doc
      .font("Helvetica")
      .fontSize(10.5)
      .fillColor(COLORS.ink)
      .text(stripMarkdown(s.content_markdown), {
        lineGap: 2,
      });
    doc.moveDown(0.5);
  }

  // If we trimmed sections, indicate it.
  if (usableSections.length < onePager.sections.length) {
    doc
      .font("Helvetica-Oblique")
      .fontSize(9)
      .fillColor(COLORS.muted)
      .text(
        `(${onePager.sections.length - usableSections.length} additional section${onePager.sections.length - usableSections.length === 1 ? "" : "s"} truncated — see full review)`,
      );
  }

  // ---- Footer band, anchored to bottom ----
  const footerY = doc.page.height - PAGE_OPTS.margins.bottom + 16;
  doc
    .font("Helvetica")
    .fontSize(8)
    .fillColor(COLORS.muted)
    .text(KILN_DISCLAIMER, PAGE_OPTS.margins.left, footerY - 30, {
      width: doc.page.width - PAGE_OPTS.margins.left - PAGE_OPTS.margins.right,
      align: "left",
    });
  doc
    .font("Helvetica")
    .fontSize(8)
    .fillColor(COLORS.muted)
    .text(
      `Generated by Kiln · ${appUrl}/deals/${deal.id} · ${input.generatedAt.toISOString().slice(0, 10)} · ${approval.approval_chain.length}-step approval chain (~${approval.expected_cycle_time_business_days} business days)`,
      PAGE_OPTS.margins.left,
      footerY,
      {
        width: doc.page.width - PAGE_OPTS.margins.left - PAGE_OPTS.margins.right,
        align: "left",
      },
    );

  doc.end();
  await closed;

  // No-op reference to silence the "remainingHeightAtStart unused" lint when
  // we eventually want to reference it for layout debugging.
  void remainingHeightAtStart;

  const buffer = Buffer.concat(chunks);
  return {
    buffer,
    contentType: "application/pdf",
    filename: artifactFilename(input, "approval-one-pager"),
    byteLength: buffer.byteLength,
  };
}

function metadataLine(input: ArtifactInput): string {
  const { deal } = input;
  const acv = formatMoney(deal.acv);
  const tcv = formatMoney(deal.tcv);
  return `ACV ${acv}  ·  TCV ${tcv}  ·  Term ${deal.term_months}mo  ·  ${humanizeDealType(deal.deal_type)}  ·  AE ${deal.ae_owner}  ·  ${input.generatedAt.toISOString().slice(0, 10)}`;
}

function rule(doc: typeof PDFDocument.prototype) {
  const left = PAGE_OPTS.margins.left;
  const right = doc.page.width - PAGE_OPTS.margins.right;
  doc
    .strokeColor(COLORS.border)
    .lineWidth(0.5)
    .moveTo(left, doc.y)
    .lineTo(right, doc.y)
    .stroke();
}

function remainingHeight(doc: typeof PDFDocument.prototype): number {
  return doc.page.height - PAGE_OPTS.margins.bottom - doc.y - 50; // -50 reserves footer band
}

// Estimate per-section height empirically (1px ≈ 1.4 chars at 10.5pt) and
// drop trailing sections that wouldn't fit. Keeps the artifact single-page.
function trimSectionsToFit(
  doc: typeof PDFDocument.prototype,
  sections: { heading: string; content_markdown: string }[],
): { heading: string; content_markdown: string }[] {
  const usableWidth =
    doc.page.width - PAGE_OPTS.margins.left - PAGE_OPTS.margins.right;
  const charsPerLine = Math.max(40, Math.floor(usableWidth / 5.2));
  let budget = remainingHeight(doc);
  const out: typeof sections = [];
  for (const s of sections) {
    const stripped = stripMarkdown(s.content_markdown);
    const estLines = Math.ceil(stripped.length / charsPerLine) + 1;
    const sectionHeight = 14 + estLines * 13 + 14; // heading + body + spacing
    if (sectionHeight > budget && out.length > 0) break;
    budget -= sectionHeight;
    out.push(s);
  }
  return out;
}

function formatMoney(n: number): string {
  if (n >= 1_000_000) return `$${(n / 1_000_000).toFixed(2)}M`;
  if (n >= 1_000) return `$${Math.round(n / 1_000)}K`;
  return `$${n.toLocaleString()}`;
}

function humanizeDealType(t: string): string {
  return t.replace(/_/g, " ").replace(/\b\w/g, (c) => c.toUpperCase());
}

// Cheap markdown → text. The Comms agent emits short markdown with **, _,
// `, [text](url), and bullets. Strip syntax but preserve content.
function stripMarkdown(s: string): string {
  return s
    .replace(/```[\s\S]*?```/g, "")
    .replace(/`([^`]+)`/g, "$1")
    .replace(/\*\*([^*]+)\*\*/g, "$1")
    .replace(/__([^_]+)__/g, "$1")
    .replace(/\*([^*]+)\*/g, "$1")
    .replace(/_([^_]+)_/g, "$1")
    .replace(/\[([^\]]+)\]\([^)]+\)/g, "$1")
    .replace(/^\s*[-*•]\s+/gm, "• ")
    .replace(/^#{1,6}\s+/gm, "")
    .trim();
}
