import type { DealWithCustomer } from "@/lib/db/queries";
import type {
  ApprovalOutput,
  Asc606Output,
  CommsOutput,
  PricingOutput,
  RedlineOutput,
} from "@/lib/agents/schemas";

// Shared payload every document template accepts. Constructed by the artifact
// route from a stored deal_review row + the deal's CRM record.
export interface ArtifactInput {
  deal: DealWithCustomer;
  pricing: PricingOutput;
  asc606: Asc606Output;
  redline: RedlineOutput;
  approval: ApprovalOutput;
  comms: CommsOutput;
  synthesis: string;
  reviewId: string;
  appUrl: string;
  generatedAt: Date;
}

export interface ArtifactBuffer {
  buffer: Buffer;
  contentType: string;
  filename: string;
  // Lower-bound estimate used for "?MB · download" UI affordance.
  byteLength: number;
}

export interface ArtifactString {
  body: string;
  contentType: string;
  filename: string;
  byteLength: number;
}

export type ArtifactType =
  | "redlined-msa"
  | "order-form"
  | "ae-email"
  | "customer-email"
  | "approval-one-pager"
  | "financial-model";

export const ARTIFACT_LABELS: Record<ArtifactType, string> = {
  "redlined-msa": "Redlined MSA",
  "order-form": "Order Form",
  "ae-email": "AE Email",
  "customer-email": "Customer Email",
  "approval-one-pager": "Approval One-Pager",
  "financial-model": "Financial Model",
};

export const ARTIFACT_EXTENSIONS: Record<ArtifactType, string> = {
  "redlined-msa": "docx",
  "order-form": "pdf",
  "ae-email": "eml",
  "customer-email": "eml",
  "approval-one-pager": "pdf",
  "financial-model": "xlsx",
};

// Build a sanitized, deal-scoped filename like "anthropic-q1-expansion-msa.docx".
export function artifactFilename(
  input: Pick<ArtifactInput, "deal">,
  type: ArtifactType,
): string {
  const slug = (input.deal.customer.name + "-" + input.deal.name)
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 64);
  const suffix: Record<ArtifactType, string> = {
    "redlined-msa": "redlined-msa",
    "order-form": "order-form",
    "ae-email": "ae-email",
    "customer-email": "customer-email",
    "approval-one-pager": "approval-one-pager",
    "financial-model": "financial-model",
  };
  return `${slug}-${suffix[type]}.${ARTIFACT_EXTENSIONS[type]}`;
}

export const KILN_DISCLAIMER =
  "This document was generated by an AI system as a demonstration. Final approval requires human review and applicable jurisdictional legal review.";
