import type { DB } from "@/lib/db/client";

export type CustomerSeed = {
  id: string;
  name: string;
  domain: string;
  segment: "enterprise" | "mid_market" | "plg_self_serve";
  employee_count: number;
  industry: string;
  hq_country: string;
  funding_stage: string | null;
  arr_estimate: number | null;
  health_score: number | null;
  is_real: 0 | 1;
};

// 6 real public companies that match Clay's ICP. These give the pipeline
// view immediate credibility — a deal-desk hire scanning the list should
// recognize the names.
const real: CustomerSeed[] = [
  {
    id: "cust_anthropic",
    name: "Anthropic",
    domain: "anthropic.com",
    segment: "enterprise",
    employee_count: 1500,
    industry: "AI/ML",
    hq_country: "US",
    funding_stage: "Late Stage Private",
    arr_estimate: 4_000_000_000,
    health_score: 88,
    is_real: 1,
  },
  {
    id: "cust_notion",
    name: "Notion",
    domain: "notion.so",
    segment: "mid_market",
    employee_count: 620,
    industry: "Productivity SaaS",
    hq_country: "US",
    funding_stage: "Series C",
    arr_estimate: 500_000_000,
    health_score: 79,
    is_real: 1,
  },
  {
    id: "cust_ramp",
    name: "Ramp",
    domain: "ramp.com",
    segment: "mid_market",
    employee_count: 950,
    industry: "Fintech",
    hq_country: "US",
    funding_stage: "Series E",
    arr_estimate: 700_000_000,
    health_score: 84,
    is_real: 1,
  },
  {
    id: "cust_verkada",
    name: "Verkada",
    domain: "verkada.com",
    segment: "mid_market",
    employee_count: 2200,
    industry: "Physical Security / IoT",
    hq_country: "US",
    funding_stage: "Series E",
    arr_estimate: 600_000_000,
    health_score: 71,
    is_real: 1,
  },
  {
    id: "cust_intercom",
    name: "Intercom",
    domain: "intercom.com",
    segment: "enterprise",
    employee_count: 900,
    industry: "Customer Messaging SaaS",
    hq_country: "US",
    funding_stage: "Late Stage Private",
    arr_estimate: 350_000_000,
    health_score: 66,
    is_real: 1,
  },
  {
    id: "cust_gong",
    name: "Gong",
    domain: "gong.io",
    segment: "enterprise",
    employee_count: 1300,
    industry: "Revenue Intelligence",
    hq_country: "US",
    funding_stage: "Series E",
    arr_estimate: 350_000_000,
    health_score: 81,
    is_real: 1,
  },
];

// 34 fictional customers split: 8 enterprise + 12 mid-market + 14 plg.
// Names chosen to sound plausible and avoid wordplay.
const fictionalEnterprise: CustomerSeed[] = [
  {
    id: "cust_tideline_logistics",
    name: "Tideline Logistics",
    domain: "tidelinelogistics.com",
    segment: "enterprise",
    employee_count: 12_400,
    industry: "Logistics",
    hq_country: "US",
    funding_stage: "Public",
    arr_estimate: 2_100_000_000,
    health_score: 73,
    is_real: 0,
  },
  {
    id: "cust_helix_diagnostics",
    name: "Helix Diagnostics",
    domain: "helixdx.com",
    segment: "enterprise",
    employee_count: 6500,
    industry: "Healthtech",
    hq_country: "US",
    funding_stage: "Public",
    arr_estimate: 1_400_000_000,
    health_score: 68,
    is_real: 0,
  },
  {
    id: "cust_voltspring",
    name: "Voltspring Energy",
    domain: "voltspring.com",
    segment: "enterprise",
    employee_count: 8200,
    industry: "Climate / Energy",
    hq_country: "US",
    funding_stage: "Public",
    arr_estimate: 3_800_000_000,
    health_score: 74,
    is_real: 0,
  },
  {
    id: "cust_meridian_insure",
    name: "Meridian Insurance Group",
    domain: "meridianinsure.com",
    segment: "enterprise",
    employee_count: 7200,
    industry: "Insurtech",
    hq_country: "US",
    funding_stage: "Public",
    arr_estimate: 2_600_000_000,
    health_score: 62,
    is_real: 0,
  },
  {
    id: "cust_cantilever_capital",
    name: "Cantilever Capital",
    domain: "cantilever.capital",
    segment: "enterprise",
    employee_count: 5500,
    industry: "Fintech / Asset Management",
    hq_country: "US",
    funding_stage: "Public",
    arr_estimate: 4_900_000_000,
    health_score: 77,
    is_real: 0,
  },
  {
    id: "cust_polymath_robotics",
    name: "Polymath Robotics",
    domain: "polymathrobotics.com",
    segment: "enterprise",
    employee_count: 9100,
    industry: "Manufacturing / Robotics",
    hq_country: "US",
    funding_stage: "Late Stage Private",
    arr_estimate: 1_800_000_000,
    health_score: 80,
    is_real: 0,
  },
  {
    id: "cust_cipher_co",
    name: "Cipher & Co.",
    domain: "cipherco.com",
    segment: "enterprise",
    employee_count: 5800,
    industry: "Cybersecurity",
    hq_country: "US",
    funding_stage: "Public",
    arr_estimate: 1_300_000_000,
    health_score: 70,
    is_real: 0,
  },
  {
    id: "cust_northstar_defense",
    name: "Northstar Defense Systems",
    domain: "northstar-defense.com",
    segment: "enterprise",
    employee_count: 6300,
    industry: "Defense / Cybersecurity",
    hq_country: "US",
    funding_stage: "Public",
    arr_estimate: 2_200_000_000,
    health_score: 65,
    is_real: 0,
  },
];

const fictionalMidMarket: CustomerSeed[] = [
  {
    id: "cust_tessera_health",
    name: "Tessera Health",
    domain: "tesserahealth.com",
    segment: "mid_market",
    employee_count: 1200,
    industry: "Healthtech",
    hq_country: "US",
    funding_stage: "Series C",
    arr_estimate: 95_000_000,
    health_score: 58,
    is_real: 0,
  },
  {
    id: "cust_northbeam_mortgage",
    name: "Northbeam Mortgage",
    domain: "northbeammortgage.com",
    segment: "mid_market",
    employee_count: 850,
    industry: "Fintech / Mortgage",
    hq_country: "US",
    funding_stage: "Series C",
    arr_estimate: 70_000_000,
    health_score: 42,
    is_real: 0,
  },
  {
    id: "cust_pebblebrook_logistics",
    name: "Pebblebrook Logistics",
    domain: "pebblebrook.io",
    segment: "mid_market",
    employee_count: 1100,
    industry: "Logistics",
    hq_country: "US",
    funding_stage: "Series B",
    arr_estimate: 60_000_000,
    health_score: 72,
    is_real: 0,
  },
  {
    id: "cust_lattice_networks",
    name: "Lattice Networks",
    domain: "latticenet.io",
    segment: "mid_market",
    employee_count: 720,
    industry: "Cybersecurity",
    hq_country: "US",
    funding_stage: "Series C",
    arr_estimate: 80_000_000,
    health_score: 76,
    is_real: 0,
  },
  {
    id: "cust_glacial_insure",
    name: "Glacial Insurance",
    domain: "glacialinsure.com",
    segment: "mid_market",
    employee_count: 950,
    industry: "Insurtech",
    hq_country: "US",
    funding_stage: "Series B",
    arr_estimate: 55_000_000,
    health_score: 64,
    is_real: 0,
  },
  {
    id: "cust_saffron_ventures",
    name: "Saffron Ventures",
    domain: "saffron.vc",
    segment: "mid_market",
    employee_count: 340,
    industry: "Fintech / VC Ops",
    hq_country: "US",
    funding_stage: "Series B",
    arr_estimate: 40_000_000,
    health_score: 81,
    is_real: 0,
  },
  {
    id: "cust_ironhold",
    name: "Ironhold Industries",
    domain: "ironhold.com",
    segment: "mid_market",
    employee_count: 1800,
    industry: "Manufacturing",
    hq_country: "US",
    funding_stage: "Series D",
    arr_estimate: 110_000_000,
    health_score: 69,
    is_real: 0,
  },
  {
    id: "cust_quill_education",
    name: "Quill Education",
    domain: "quill.edu",
    segment: "mid_market",
    employee_count: 540,
    industry: "Edtech",
    hq_country: "US",
    funding_stage: "Series B",
    arr_estimate: 45_000_000,
    health_score: 60,
    is_real: 0,
  },
  {
    id: "cust_kindred_therapy",
    name: "Kindred Therapy",
    domain: "kindredtherapy.com",
    segment: "mid_market",
    employee_count: 460,
    industry: "Telehealth",
    hq_country: "US",
    funding_stage: "Series B",
    arr_estimate: 38_000_000,
    health_score: 75,
    is_real: 0,
  },
  {
    id: "cust_maquette_studios",
    name: "Maquette Studios",
    domain: "maquette.studio",
    segment: "mid_market",
    employee_count: 380,
    industry: "Adtech",
    hq_country: "US",
    funding_stage: "Series B",
    arr_estimate: 32_000_000,
    health_score: 51,
    is_real: 0,
  },
  {
    id: "cust_olmstead_realty",
    name: "Olmstead Realty",
    domain: "olmsteadrealty.com",
    segment: "mid_market",
    employee_count: 880,
    industry: "Proptech",
    hq_country: "US",
    funding_stage: "Series C",
    arr_estimate: 65_000_000,
    health_score: 67,
    is_real: 0,
  },
  {
    id: "cust_coastline_bank",
    name: "Coastline Community Bank",
    domain: "coastlinebank.com",
    segment: "mid_market",
    employee_count: 2200,
    industry: "Fintech / Regional Bank",
    hq_country: "US",
    funding_stage: "Public",
    arr_estimate: 240_000_000,
    health_score: 74,
    is_real: 0,
  },
];

const fictionalPlg: CustomerSeed[] = [
  {
    id: "cust_reverberate_growth",
    name: "Reverberate Growth",
    domain: "reverberategrowth.com",
    segment: "plg_self_serve",
    employee_count: 80,
    industry: "GTM Agency",
    hq_country: "US",
    funding_stage: "Bootstrapped",
    arr_estimate: 12_000_000,
    health_score: 88,
    is_real: 0,
  },
  {
    id: "cust_hightide_devtools",
    name: "Hightide Devtools",
    domain: "hightide.dev",
    segment: "plg_self_serve",
    employee_count: 45,
    industry: "Developer Tools",
    hq_country: "US",
    funding_stage: "Series A",
    arr_estimate: 8_000_000,
    health_score: 82,
    is_real: 0,
  },
  {
    id: "cust_slate_analytics",
    name: "Slate Analytics",
    domain: "slateanalytics.io",
    segment: "plg_self_serve",
    employee_count: 65,
    industry: "Analytics SaaS",
    hq_country: "US",
    funding_stage: "Series A",
    arr_estimate: 6_500_000,
    health_score: 70,
    is_real: 0,
  },
  {
    id: "cust_beanstalk_ai",
    name: "Beanstalk AI",
    domain: "beanstalk.ai",
    segment: "plg_self_serve",
    employee_count: 25,
    industry: "AI/ML",
    hq_country: "US",
    funding_stage: "Seed",
    arr_estimate: 2_500_000,
    health_score: 78,
    is_real: 0,
  },
  {
    id: "cust_makers_loom",
    name: "Maker's Loom",
    domain: "makersloom.com",
    segment: "plg_self_serve",
    employee_count: 110,
    industry: "Ecommerce SaaS",
    hq_country: "US",
    funding_stage: "Series A",
    arr_estimate: 14_000_000,
    health_score: 65,
    is_real: 0,
  },
  {
    id: "cust_sparrow_labs",
    name: "Sparrow Labs",
    domain: "sparrowlabs.io",
    segment: "plg_self_serve",
    employee_count: 32,
    industry: "Developer Tools",
    hq_country: "US",
    funding_stage: "Seed",
    arr_estimate: 3_200_000,
    health_score: 73,
    is_real: 0,
  },
  {
    id: "cust_filament_studios",
    name: "Filament Studios",
    domain: "filament.studio",
    segment: "plg_self_serve",
    employee_count: 55,
    industry: "Design Tooling",
    hq_country: "US",
    funding_stage: "Series A",
    arr_estimate: 5_400_000,
    health_score: 79,
    is_real: 0,
  },
  {
    id: "cust_underwood_legal",
    name: "Underwood Legal",
    domain: "underwoodlegal.com",
    segment: "plg_self_serve",
    employee_count: 90,
    industry: "Legaltech",
    hq_country: "US",
    funding_stage: "Series A",
    arr_estimate: 9_500_000,
    health_score: 71,
    is_real: 0,
  },
  {
    id: "cust_rookery_hr",
    name: "Rookery HR",
    domain: "rookeryhr.com",
    segment: "plg_self_serve",
    employee_count: 70,
    industry: "HR Tech",
    hq_country: "US",
    funding_stage: "Series A",
    arr_estimate: 7_200_000,
    health_score: 56,
    is_real: 0,
  },
  {
    id: "cust_sunfish_media",
    name: "Sunfish Media",
    domain: "sunfishmedia.com",
    segment: "plg_self_serve",
    employee_count: 140,
    industry: "Media Analytics",
    hq_country: "US",
    funding_stage: "Series B",
    arr_estimate: 18_000_000,
    health_score: 63,
    is_real: 0,
  },
  {
    id: "cust_bristlecone_climate",
    name: "Bristlecone Climate",
    domain: "bristleconeclimate.com",
    segment: "plg_self_serve",
    employee_count: 28,
    industry: "Climate SaaS",
    hq_country: "US",
    funding_stage: "Seed",
    arr_estimate: 1_800_000,
    health_score: 84,
    is_real: 0,
  },
  {
    id: "cust_stillwater_insure",
    name: "Stillwater Insurance",
    domain: "stillwaterinsure.com",
    segment: "plg_self_serve",
    employee_count: 175,
    industry: "Insurtech",
    hq_country: "US",
    funding_stage: "Series B",
    arr_estimate: 22_000_000,
    health_score: 59,
    is_real: 0,
  },
  {
    id: "cust_quokka_travel",
    name: "Quokka Travel",
    domain: "quokkatravel.com",
    segment: "plg_self_serve",
    employee_count: 60,
    industry: "Travel Tech",
    hq_country: "US",
    funding_stage: "Series A",
    arr_estimate: 6_000_000,
    health_score: 47,
    is_real: 0,
  },
  {
    id: "cust_halibut_marketplaces",
    name: "Halibut Marketplaces",
    domain: "halibut.market",
    segment: "plg_self_serve",
    employee_count: 38,
    industry: "Marketplace Ops",
    hq_country: "US",
    funding_stage: "Seed",
    arr_estimate: 3_400_000,
    health_score: 72,
    is_real: 0,
  },
];

export const customers: CustomerSeed[] = [
  ...real,
  ...fictionalEnterprise,
  ...fictionalMidMarket,
  ...fictionalPlg,
];

export function seedCustomers(db: DB): number {
  const insert = db.prepare(`
    INSERT OR REPLACE INTO customers (
      id, name, domain, segment, employee_count, industry, hq_country,
      funding_stage, arr_estimate, health_score, is_real
    ) VALUES (
      @id, @name, @domain, @segment, @employee_count, @industry, @hq_country,
      @funding_stage, @arr_estimate, @health_score, @is_real
    )
  `);

  const insertAll = db.transaction((rows: CustomerSeed[]) => {
    for (const row of rows) insert.run(row);
  });

  insertAll(customers);
  return customers.length;
}
