import type { DB } from "@/lib/db/client";
import type { DealSeed } from "./scenarios/types";

// 35 non-hero deals: 4 discovery + 8 proposal + 10 negotiation
// + 8 closed_won + 5 closed_lost. Negotiation/proposal stages get
// AE-voice customer_request fields per the realism bar.

const negotiation: DealSeed[] = [
  {
    id: "deal_ramp_2026_q2_expansion",
    customer_id: "cust_ramp",
    name: "Q2 Expansion — Inbound SDR AI Enrichment",
    deal_type: "expansion",
    stage: "negotiation",
    acv: 420_000,
    tcv: 840_000,
    term_months: 24,
    ramp_schedule_json: null,
    list_price: 480_000,
    proposed_price: 420_000,
    discount_pct: 12.5,
    discount_reason:
      "Strategic fintech expansion (45 SDR seats). Multi-year commit with SLA upgrade trade-off.",
    payment_terms: "annual_upfront",
    payment_terms_notes: null,
    pricing_model: "subscription",
    usage_commit_units: null,
    overage_rate: null,
    non_standard_clauses: JSON.stringify([
      "mfn_against_named_competitors_3",
      "uptime_sla_99_95_with_credits",
      "data_processing_amendment_eu_uk",
    ]),
    ae_owner: "Maya Chen",
    ae_manager: "Sarah Goldstein",
    competitive_context:
      "Apollo offered Ramp a 24-month flat fee at ~$300K. Strategic to defend; Ramp is a flagship fintech reference.",
    customer_request:
      "Ramp's RevOps wants to add Clay enrichment + AI scoring across their inbound SDR pipeline (45 reps). They're asking for an MFN limited to three named competitors (Apollo, Clearbit, ZoomInfo Sales OS), a 99.95% uptime SLA with service credits at the 99.5% breakpoint, and a refreshed DPA with both EU and UK data subprocessor lists. CRO has signed off on $420K conditional on the SLA upgrade — Procurement is the remaining gating item.",
    close_date: "2026-06-15",
    is_scenario: 0,
  },
  {
    id: "deal_intercom_2026_ai_workflows",
    customer_id: "cust_intercom",
    name: "AI Workflows Module Add-On",
    deal_type: "expansion",
    stage: "negotiation",
    acv: 260_000,
    tcv: 260_000,
    term_months: 12,
    ramp_schedule_json: JSON.stringify([
      { month: 1, amount: 10833 },
      { month: 2, amount: 10833 },
      { month: 3, amount: 10833 },
      { month: 4, amount: 10833 },
      { month: 5, amount: 10833 },
      { month: 6, amount: 10833 },
      { month: 7, amount: 21667 },
      { month: 8, amount: 21667 },
      { month: 9, amount: 21667 },
      { month: 10, amount: 21667 },
      { month: 11, amount: 21667 },
      { month: 12, amount: 21667 },
    ]),
    list_price: 290_000,
    proposed_price: 260_000,
    discount_pct: 10.3,
    discount_reason:
      "Pilot-to-production milestone pricing trade. Half-price during pilot, triggered to full on workflow-volume milestone.",
    payment_terms: "annual_upfront",
    payment_terms_notes:
      "First 6 months at 50% of full ACV (pilot). Triggers to full price upon hitting 250K successful workflow runs/month for two consecutive months.",
    pricing_model: "hybrid",
    usage_commit_units: 800_000,
    overage_rate: 0.0012,
    non_standard_clauses: JSON.stringify([
      "pilot_to_production_milestone_pricing",
      "co_development_engineering_review_quarterly",
    ]),
    ae_owner: "Devon Wright",
    ae_manager: "Sarah Goldstein",
    competitive_context:
      "Intercom is also building parts in-house. Risk = they pull this back to engineering if the milestone trigger isn't tight.",
    customer_request:
      "Intercom's product engineering wants Clay's AI workflow module for pre-fill on Fin's outbound. They're asking the first 6 months be priced as a 'pilot' (50% of $260K, ~$130K annualized) with full price triggered on hitting 250K successful workflow runs/month, plus a quarterly engineering review with our team. AE has soft-committed to milestone pricing — needs RevOps eyes on the trigger language.",
    close_date: "2026-06-01",
    is_scenario: 0,
  },
  {
    id: "deal_cipher_2026_multi_region",
    customer_id: "cust_cipher_co",
    name: "Multi-Region Enterprise New Logo",
    deal_type: "new_logo",
    stage: "negotiation",
    acv: 640_000,
    tcv: 1_920_000,
    term_months: 36,
    ramp_schedule_json: null,
    list_price: 760_000,
    proposed_price: 640_000,
    discount_pct: 15.8,
    discount_reason:
      "3-year enterprise commit (cybersecurity vertical). Multi-region deployment + heavy compliance scope.",
    payment_terms: "annual_upfront",
    payment_terms_notes:
      "Annual upfront per region; consolidated invoice across US-East, eu-central-1, ap-southeast-1.",
    pricing_model: "subscription",
    usage_commit_units: null,
    overage_rate: null,
    non_standard_clauses: JSON.stringify([
      "data_residency_us_eu_apac",
      "annual_pen_test_review_clause",
      "ofac_sanctions_screening_addendum",
    ]),
    ae_owner: "Priya Shankar",
    ae_manager: "Marcus Reilly",
    competitive_context:
      "Bake-off with ZoomInfo Enterprise (incumbent) and a Clearbit/HubSpot bundled bid.",
    customer_request:
      "Cipher's CISO requires deployment in three regions (US-East, eu-central-1, ap-southeast-1) with regional data segregation, an annual pentest review obligation we provide to them, and an OFAC sanctions screening addendum that covers any partner Clay calls into during enrichment. Their security team is thorough — they've already returned our standard MSA with 47 tracked changes. Compensating event: their CRO is willing to commit to a 3-year term if we accept the residency and pen-test asks.",
    close_date: "2026-07-30",
    is_scenario: 0,
  },
  {
    id: "deal_cantilever_2026_compliance",
    customer_id: "cust_cantilever_capital",
    name: "FY26 New Logo — Compliance Stack",
    deal_type: "new_logo",
    stage: "negotiation",
    acv: 560_000,
    tcv: 1_120_000,
    term_months: 24,
    ramp_schedule_json: null,
    list_price: 620_000,
    proposed_price: 560_000,
    discount_pct: 9.7,
    discount_reason:
      "Regulated fintech (asset mgmt). 2-year enterprise commit anchored against high compliance/security scope concessions.",
    payment_terms: "annual_upfront",
    payment_terms_notes: null,
    pricing_model: "subscription",
    usage_commit_units: null,
    overage_rate: null,
    non_standard_clauses: JSON.stringify([
      "sec_finra_audit_logging_full_export",
      "named_third_party_processor_whitelist",
      "indemnity_cap_3x_aggregate_fees",
    ]),
    ae_owner: "Maya Chen",
    ae_manager: "Sarah Goldstein",
    competitive_context:
      "Their incumbent is a custom-built tool from 2019 that no longer scales; risk is rebuilding internally instead of buying.",
    customer_request:
      "Cantilever's General Counsel is requiring (a) full audit log export weekly to their SOC/SIEM in CEF format, (b) a whitelist where any third-party data processor we route enrichment through has to be pre-approved (they sent the initial whitelist, ~12 vendors), and (c) an indemnity cap raised to 3x aggregate fees. Their AE-side advocate is calling this 'the standard ask for any vendor onboarding into our regulated stack.' Our standard cap is 12mo fees.",
    close_date: "2026-07-10",
    is_scenario: 0,
  },
  {
    id: "deal_pebblebrook_2026_expansion",
    customer_id: "cust_pebblebrook_logistics",
    name: "Expansion — LTL + Last-Mile Lines",
    deal_type: "expansion",
    stage: "negotiation",
    acv: 190_000,
    tcv: 380_000,
    term_months: 24,
    ramp_schedule_json: null,
    list_price: 215_000,
    proposed_price: 190_000,
    discount_pct: 11.6,
    discount_reason:
      "Mid-market expansion from 18 → 60 seats across two new lines (LTL, last-mile). Non-standard partner reservation traded against 24mo commit.",
    payment_terms: "annual_upfront",
    payment_terms_notes: null,
    pricing_model: "subscription",
    usage_commit_units: null,
    overage_rate: null,
    non_standard_clauses: JSON.stringify([
      "msp_partner_reservation_3rd_party",
      "training_credits_included_50_seats",
    ]),
    ae_owner: "Devon Wright",
    ae_manager: "Sarah Goldstein",
    competitive_context:
      "No active vendor competitor — internal alternative is Outreach + manual spreadsheets, which their VP Ops is actively trying to retire.",
    customer_request:
      "Pebblebrook's ops team wants to scale from 18 seats to 60 seats across two new business lines (LTL and last-mile). They're asking for: (1) a clause reserving the right to designate one MSP partner ('Compass Operations') as a co-licensee at no additional fee, and (2) 50 free seats of training credits redeemable through end of contract. AE proposed both verbally; needs paper.",
    close_date: "2026-06-20",
    is_scenario: 0,
  },
  {
    id: "deal_lattice_2026_security_review",
    customer_id: "cust_lattice_networks",
    name: "Expansion — Security Operations Add-On",
    deal_type: "expansion",
    stage: "negotiation",
    acv: 165_000,
    tcv: 330_000,
    term_months: 24,
    ramp_schedule_json: null,
    list_price: 180_000,
    proposed_price: 165_000,
    discount_pct: 8.3,
    discount_reason:
      "Cyber-vertical reference customer. Modest discount in exchange for public reference rights and quarterly security reviews.",
    payment_terms: "annual_upfront",
    payment_terms_notes: null,
    pricing_model: "subscription",
    usage_commit_units: null,
    overage_rate: null,
    non_standard_clauses: JSON.stringify([
      "security_review_quarterly",
      "ip_address_allowlist_enforcement",
      "subprocessor_change_30day_notice",
    ]),
    ae_owner: "Priya Shankar",
    ae_manager: "Marcus Reilly",
    competitive_context:
      "No active competitor — but their Board has asked them to consolidate vendor count by 30% in FY26.",
    customer_request:
      "Lattice's security team wants quarterly security reviews with our InfoSec on call, an enforced IP allowlist for our outbound webhook calls (their list, ~22 IPs), and 30-day advance notice on any new subprocessor we add. AE confirmed all three are doable; need to scope quarterly review time commitment. Customer is referenceable — they've publicly named Clay as a vendor on their last quarterly investor call.",
    close_date: "2026-06-25",
    is_scenario: 0,
  },
  {
    id: "deal_saffron_2026_deferred_billing",
    customer_id: "cust_saffron_ventures",
    name: "VC Platform New Logo (Deferred Start)",
    deal_type: "new_logo",
    stage: "negotiation",
    acv: 85_000,
    tcv: 170_000,
    term_months: 24,
    ramp_schedule_json: null,
    list_price: 95_000,
    proposed_price: 85_000,
    discount_pct: 10.5,
    discount_reason:
      "Mid-market VC ops. Deferred-billing-to-fund-close concession unlocked CFO engagement.",
    payment_terms: "custom",
    payment_terms_notes:
      "Sign now; first invoice issued at fund close (target 2026-09-30). Term clock starts at first invoice.",
    pricing_model: "subscription",
    usage_commit_units: null,
    overage_rate: null,
    non_standard_clauses: JSON.stringify([
      "deferred_billing_until_fund_close_q3",
      "fund_admin_user_seats_included",
    ]),
    ae_owner: "Devon Wright",
    ae_manager: "Sarah Goldstein",
    competitive_context:
      "Currently using Affinity for relationship intel; they want enrichment + waterfalling on top. Affinity is sticky on CRM side, not sticky on enrichment.",
    customer_request:
      "Saffron's CFO is asking us to defer billing until their Q3 fund close — they have committed capital but timing is fund-driven, not calendar-driven. They've offered to sign now and start invoicing post-close (estimated 2026-09-30). They also want 4 fund admin user seats included gratis (they're shared with their fund administrator, an external firm). AE says deferred billing was 'the way we got their CFO to engage.'",
    close_date: "2026-08-15",
    is_scenario: 0,
  },
  {
    id: "deal_ironhold_2026_price_cap",
    customer_id: "cust_ironhold",
    name: "FY26 New Logo — Manufacturing Procurement",
    deal_type: "new_logo",
    stage: "negotiation",
    acv: 220_000,
    tcv: 660_000,
    term_months: 36,
    ramp_schedule_json: null,
    list_price: 245_000,
    proposed_price: 220_000,
    discount_pct: 10.2,
    discount_reason:
      "Mature procurement buyer (manufacturing). 3-year commit traded against 5% YoY price-increase cap.",
    payment_terms: "annual_upfront",
    payment_terms_notes: null,
    pricing_model: "subscription",
    usage_commit_units: null,
    overage_rate: null,
    non_standard_clauses: JSON.stringify([
      "price_increase_cap_5pct_yoy",
      "expansion_seat_pricing_locked_2026",
    ]),
    ae_owner: "Maya Chen",
    ae_manager: "Sarah Goldstein",
    competitive_context:
      "Their fallback is renewing with their existing Apollo + ZoomInfo combo at flat $180K total.",
    customer_request:
      "Ironhold's Procurement is a mature buyer; they're asking for a 5% YoY price increase cap (we can pass through CPI/inflation up to 5% but not above) and 2026-locked pricing on any expansion seats added in years 2-3. They're clear that the YoY cap is a hard ask — they've walked from two prior vendors over this term. Their CFO wants to sign before their fiscal year end (June 30).",
    close_date: "2026-06-28",
    is_scenario: 0,
  },
  {
    id: "deal_makers_loom_2026_conversion",
    customer_id: "cust_makers_loom",
    name: "Self-Serve to Enterprise — DTC Holiday Pause",
    deal_type: "expansion",
    stage: "negotiation",
    acv: 95_000,
    tcv: 190_000,
    term_months: 24,
    ramp_schedule_json: JSON.stringify([
      { month: 1, amount: 1979 },
      { month: 2, amount: 1979 },
      { month: 3, amount: 1979 },
      { month: 4, amount: 7917 },
      { month: 5, amount: 7917 },
      { month: 6, amount: 7917 },
      { month: 7, amount: 7917 },
      { month: 8, amount: 7917 },
      { month: 9, amount: 7917 },
      { month: 10, amount: 7917 },
      { month: 11, amount: 7917 },
      { month: 12, amount: 7917 },
    ]),
    list_price: 105_000,
    proposed_price: 95_000,
    discount_pct: 9.5,
    discount_reason:
      "PLG-to-enterprise conversion (9 → 24 seats). 3-month ramp aligned to hiring + holiday pause clause.",
    payment_terms: "annual_upfront",
    payment_terms_notes:
      "Months 1-3 billed at 25% of full price (ramp). Months 4-12 at full price.",
    pricing_model: "hybrid",
    usage_commit_units: 500_000,
    overage_rate: 0.001,
    non_standard_clauses: JSON.stringify([
      "ramp_25pct_3mo",
      "pause_clause_holiday_shutdown_2_weeks",
    ]),
    ae_owner: "Devon Wright",
    ae_manager: "Sarah Goldstein",
    competitive_context:
      "Enriched.io is their cheaper alternative. Healthy customer though — 91st-percentile workflow runs/seat in our self-serve cohort.",
    customer_request:
      "Maker's Loom is converting from 9 self-serve seats to a 24-seat enterprise plan. They're asking for a 3-month ramp (25% of full price during ramp) to align with their hiring timeline, plus a 'pause clause' allowing them to pause workflow execution for 2 weeks per year during their post-Black-Friday holiday shutdown. AE has flagged the pause clause as 'something I committed to verbally but want desk to bless.'",
    close_date: "2026-06-10",
    is_scenario: 0,
  },
  {
    id: "deal_underwood_2026_services_bundle",
    customer_id: "cust_underwood_legal",
    name: "Legaltech New Logo — Services Bundle",
    deal_type: "new_logo",
    stage: "negotiation",
    acv: 115_000,
    tcv: 230_000,
    term_months: 24,
    ramp_schedule_json: null,
    list_price: 130_000,
    proposed_price: 115_000,
    discount_pct: 11.5,
    discount_reason:
      "Legaltech vertical. Services bundle scope dispute — AE went too high on pro-services hours; pulling back.",
    payment_terms: "annual_upfront",
    payment_terms_notes: null,
    pricing_model: "subscription",
    usage_commit_units: null,
    overage_rate: null,
    non_standard_clauses: JSON.stringify([
      "professional_services_60hr_bundled",
      "data_export_format_negotiated_xml_jsonld",
    ]),
    ae_owner: "Priya Shankar",
    ae_manager: "Marcus Reilly",
    competitive_context:
      "Harvey AI is the alternative; narrower scope but stronger legal-specific pretraining. Underwood's GC is comparing line-by-line.",
    customer_request:
      "Underwood's GC wants 60 hours of professional services bundled at no incremental cost (mostly for their custom legal-research workflow build), plus a contractual commitment that data export will be available in both XML and JSON-LD formats (they're standardizing on JSON-LD internally). AE went too high on the services number; pushing back to 30 bundled + 30 at 50% discount. Customer is comparing vs. Harvey AI's narrower offering.",
    close_date: "2026-07-05",
    is_scenario: 0,
  },
];

const proposal: DealSeed[] = [
  {
    id: "deal_verkada_2026_unified",
    customer_id: "cust_verkada",
    name: "RevOps + SE Unified Pricing",
    deal_type: "expansion",
    stage: "proposal",
    acv: 310_000,
    tcv: 620_000,
    term_months: 24,
    ramp_schedule_json: null,
    list_price: 340_000,
    proposed_price: 310_000,
    discount_pct: 8.8,
    discount_reason:
      "Multi-department unification (RevOps + Sales Engineering) on a single contract.",
    payment_terms: "annual_upfront",
    payment_terms_notes: null,
    pricing_model: "subscription",
    usage_commit_units: null,
    overage_rate: null,
    non_standard_clauses: JSON.stringify(["multi_dept_pricing_unified"]),
    ae_owner: "Maya Chen",
    ae_manager: "Sarah Goldstein",
    competitive_context: "No active competitor; expansion within an existing footprint.",
    customer_request:
      "Verkada's RevOps and Sales Engineering both want Clay access. Initial proposal sent Friday with unified pricing across both departments at $310K/yr. Awaiting their security team's review — typical 2-week turn for them.",
    close_date: "2026-07-20",
    is_scenario: 0,
  },
  {
    id: "deal_tideline_2026_subsidiaries",
    customer_id: "cust_tideline_logistics",
    name: "Enterprise New Logo — 4 Subsidiaries",
    deal_type: "new_logo",
    stage: "proposal",
    acv: 480_000,
    tcv: 1_440_000,
    term_months: 36,
    ramp_schedule_json: null,
    list_price: 560_000,
    proposed_price: 480_000,
    discount_pct: 14.3,
    discount_reason:
      "Multi-subsidiary consolidation. 3-year commit anchors a strategic logistics logo win.",
    payment_terms: "annual_upfront",
    payment_terms_notes:
      "Single consolidated invoice across 4 subsidiaries (Tideline Express, Freight, Last-Mile, Hub).",
    pricing_model: "subscription",
    usage_commit_units: null,
    overage_rate: null,
    non_standard_clauses: JSON.stringify([
      "multi_subsidiary_consolidated_invoice",
    ]),
    ae_owner: "Priya Shankar",
    ae_manager: "Marcus Reilly",
    competitive_context: "Greenfield — no competing vendor in the eval.",
    customer_request:
      "Tideline's CRO requested a structure covering all 4 subsidiaries (Tideline Express, Tideline Freight, Tideline Last-Mile, Tideline Hub) on a single consolidated invoice. Initial proposal sent at $480K/yr; expecting pushback on the multi-year commit.",
    close_date: "2026-08-25",
    is_scenario: 0,
  },
  {
    id: "deal_helix_2026_baa",
    customer_id: "cust_helix_diagnostics",
    name: "Healthtech Enterprise New Logo",
    deal_type: "new_logo",
    stage: "proposal",
    acv: 390_000,
    tcv: 780_000,
    term_months: 24,
    ramp_schedule_json: null,
    list_price: 440_000,
    proposed_price: 390_000,
    discount_pct: 11.4,
    discount_reason:
      "Healthtech enterprise; PHI handling adds compliance cost — modest discount to anchor logo.",
    payment_terms: "annual_upfront",
    payment_terms_notes: null,
    pricing_model: "subscription",
    usage_commit_units: null,
    overage_rate: null,
    non_standard_clauses: JSON.stringify(["baa_required", "phi_handling_addendum"]),
    ae_owner: "Devon Wright",
    ae_manager: "Sarah Goldstein",
    competitive_context: "Comparing against ZoomInfo Health-vertical bundle.",
    customer_request:
      "Helix needs a BAA executed before kickoff and PHI handling language in the MSA. Initial proposal sent at $390K. Their CISO has flagged a few subprocessor questions; preparing responses.",
    close_date: "2026-08-10",
    is_scenario: 0,
  },
  {
    id: "deal_glacial_2026_rollover",
    customer_id: "cust_glacial_insure",
    name: "Mid-Market Multi-Year Insurtech",
    deal_type: "new_logo",
    stage: "proposal",
    acv: 145_000,
    tcv: 435_000,
    term_months: 36,
    ramp_schedule_json: null,
    list_price: 165_000,
    proposed_price: 145_000,
    discount_pct: 12.1,
    discount_reason: "3-year commit in regulated insurtech vertical.",
    payment_terms: "annual_upfront",
    payment_terms_notes: null,
    pricing_model: "subscription",
    usage_commit_units: null,
    overage_rate: null,
    non_standard_clauses: JSON.stringify([
      "unused_credit_rollover_quarterly",
    ]),
    ae_owner: "Maya Chen",
    ae_manager: "Sarah Goldstein",
    competitive_context: "No active competitor — replacing in-house spreadsheets.",
    customer_request:
      "Glacial proposed at $145K/yr for 3 years. They've asked about quarterly rollover of any unused enrichment credits — pending response from us. Decision pace: their normal 6-week procurement cycle.",
    close_date: "2026-08-05",
    is_scenario: 0,
  },
  {
    id: "deal_slate_2026_upgrade",
    customer_id: "cust_slate_analytics",
    name: "PLG → Mid-Market Upgrade",
    deal_type: "expansion",
    stage: "proposal",
    acv: 52_000,
    tcv: 104_000,
    term_months: 24,
    ramp_schedule_json: null,
    list_price: 58_000,
    proposed_price: 52_000,
    discount_pct: 10.3,
    discount_reason: "Standard PLG-to-mid-market upgrade discount.",
    payment_terms: "annual_upfront",
    payment_terms_notes: null,
    pricing_model: "subscription",
    usage_commit_units: null,
    overage_rate: null,
    non_standard_clauses: null,
    ae_owner: "Devon Wright",
    ae_manager: "Sarah Goldstein",
    competitive_context: "No active competitor.",
    customer_request:
      "Slate is upgrading from 8 self-serve seats to a 22-seat mid-market plan. Standard structure proposed; awaiting their VP Sales sign-off.",
    close_date: "2026-06-30",
    is_scenario: 0,
  },
  {
    id: "deal_filament_2026_expansion",
    customer_id: "cust_filament_studios",
    name: "Founder-Led Expansion",
    deal_type: "expansion",
    stage: "proposal",
    acv: 42_000,
    tcv: 84_000,
    term_months: 24,
    ramp_schedule_json: null,
    list_price: 46_000,
    proposed_price: 42_000,
    discount_pct: 8.7,
    discount_reason: "Small mid-market expansion with founder as decision-maker.",
    payment_terms: "annual_upfront",
    payment_terms_notes: null,
    pricing_model: "subscription",
    usage_commit_units: null,
    overage_rate: null,
    non_standard_clauses: null,
    ae_owner: "Devon Wright",
    ae_manager: "Sarah Goldstein",
    competitive_context: null,
    customer_request:
      "Filament expanding from 6 seats to 14. Initial proposal sent; their founder is the decision-maker so cycle should be quick.",
    close_date: "2026-06-15",
    is_scenario: 0,
  },
  {
    id: "deal_olmstead_2026_us_only",
    customer_id: "cust_olmstead_realty",
    name: "Proptech New Logo — US-Only Processing",
    deal_type: "new_logo",
    stage: "proposal",
    acv: 130_000,
    tcv: 260_000,
    term_months: 24,
    ramp_schedule_json: null,
    list_price: 145_000,
    proposed_price: 130_000,
    discount_pct: 10.3,
    discount_reason:
      "Proptech mid-market. US-only data processing constraint adds cost; modest anchoring discount.",
    payment_terms: "annual_upfront",
    payment_terms_notes: null,
    pricing_model: "subscription",
    usage_commit_units: null,
    overage_rate: null,
    non_standard_clauses: JSON.stringify(["us_only_data_processing"]),
    ae_owner: "Maya Chen",
    ae_manager: "Sarah Goldstein",
    competitive_context: "Bake-off against an in-region proptech-vertical vendor.",
    customer_request:
      "Olmstead requires US-only data processing for compliance. Initial proposal sent; their security team is reviewing the regional commitment language.",
    close_date: "2026-07-25",
    is_scenario: 0,
  },
  {
    id: "deal_stillwater_2026_soc2",
    customer_id: "cust_stillwater_insure",
    name: "Insurtech New Logo — SOC 2 Addendum",
    deal_type: "new_logo",
    stage: "proposal",
    acv: 88_000,
    tcv: 176_000,
    term_months: 24,
    ramp_schedule_json: null,
    list_price: 100_000,
    proposed_price: 88_000,
    discount_pct: 12.0,
    discount_reason: "Small insurtech logo. Standard discount for 2-year commit.",
    payment_terms: "annual_upfront",
    payment_terms_notes: null,
    pricing_model: "subscription",
    usage_commit_units: null,
    overage_rate: null,
    non_standard_clauses: JSON.stringify(["soc2_type2_addendum"]),
    ae_owner: "Devon Wright",
    ae_manager: "Sarah Goldstein",
    competitive_context: null,
    customer_request:
      "Stillwater is asking for SOC 2 Type 2 attestation language baked into the MSA. Standard pricing proposal at $88K; awaiting their CTO review.",
    close_date: "2026-07-15",
    is_scenario: 0,
  },
];

const discovery: DealSeed[] = [
  {
    id: "deal_voltspring_2026_discovery",
    customer_id: "cust_voltspring",
    name: "Post-IPO GTM Stack Eval",
    deal_type: "new_logo",
    stage: "discovery",
    acv: 200_000,
    tcv: 200_000,
    term_months: 12,
    ramp_schedule_json: null,
    list_price: 200_000,
    proposed_price: 200_000,
    discount_pct: 0,
    discount_reason: null,
    payment_terms: "annual_upfront",
    payment_terms_notes: null,
    pricing_model: "subscription",
    usage_commit_units: null,
    overage_rate: null,
    non_standard_clauses: null,
    ae_owner: "Jamal Okafor",
    ae_manager: "Marcus Reilly",
    competitive_context: null,
    customer_request:
      "Inbound from Voltspring's GTM ops director. Currently evaluating their tech stack post-IPO. Initial discovery call scheduled for next Tuesday.",
    close_date: "2026-09-15",
    is_scenario: 0,
  },
  {
    id: "deal_meridian_2026_discovery",
    customer_id: "cust_meridian_insure",
    name: "Multi-LOB Consolidation Conversation",
    deal_type: "new_logo",
    stage: "discovery",
    acv: 350_000,
    tcv: 700_000,
    term_months: 24,
    ramp_schedule_json: null,
    list_price: 350_000,
    proposed_price: 350_000,
    discount_pct: 0,
    discount_reason: null,
    payment_terms: "annual_upfront",
    payment_terms_notes: null,
    pricing_model: "subscription",
    usage_commit_units: null,
    overage_rate: null,
    non_standard_clauses: null,
    ae_owner: "Maya Chen",
    ae_manager: "Sarah Goldstein",
    competitive_context: null,
    customer_request:
      "Referral from a prior Anthropic deal. Meridian's RevOps lead reached out wanting to talk about consolidation across their 4 LOBs. No timeline yet.",
    close_date: "2026-09-30",
    is_scenario: 0,
  },
  {
    id: "deal_sunfish_2026_discovery",
    customer_id: "cust_sunfish_media",
    name: "Inbound — Small Team Eval",
    deal_type: "new_logo",
    stage: "discovery",
    acv: 48_000,
    tcv: 48_000,
    term_months: 12,
    ramp_schedule_json: null,
    list_price: 48_000,
    proposed_price: 48_000,
    discount_pct: 0,
    discount_reason: null,
    payment_terms: "annual_upfront",
    payment_terms_notes: null,
    pricing_model: "subscription",
    usage_commit_units: null,
    overage_rate: null,
    non_standard_clauses: null,
    ae_owner: "Devon Wright",
    ae_manager: "Sarah Goldstein",
    competitive_context: null,
    customer_request:
      "Inbound from Sunfish's marketing lead via the website. Small team (~12 power users). Standard discovery process.",
    close_date: "2026-08-30",
    is_scenario: 0,
  },
  {
    id: "deal_bristlecone_2026_discovery",
    customer_id: "cust_bristlecone_climate",
    name: "Cold Outbound — Seed Stage",
    deal_type: "new_logo",
    stage: "discovery",
    acv: 24_000,
    tcv: 24_000,
    term_months: 12,
    ramp_schedule_json: null,
    list_price: 24_000,
    proposed_price: 24_000,
    discount_pct: 0,
    discount_reason: null,
    payment_terms: "annual_upfront",
    payment_terms_notes: null,
    pricing_model: "subscription",
    usage_commit_units: null,
    overage_rate: null,
    non_standard_clauses: null,
    ae_owner: "Jamal Okafor",
    ae_manager: "Marcus Reilly",
    competitive_context: null,
    customer_request:
      "Cold outbound. Founder responded; small team, tight budget. Will likely cap at $25K/yr or below.",
    close_date: "2026-09-20",
    is_scenario: 0,
  },
];

const closedWon: DealSeed[] = [
  {
    id: "deal_gong_2026q1_new_logo",
    customer_id: "cust_gong",
    name: "FY26 New Logo — Revenue Intelligence",
    deal_type: "new_logo",
    stage: "closed_won",
    acv: 620_000,
    tcv: 1_240_000,
    term_months: 24,
    ramp_schedule_json: null,
    list_price: 700_000,
    proposed_price: 620_000,
    discount_pct: 11.4,
    discount_reason:
      "Strategic enterprise logo (revenue intelligence). 2-year commit + uptime SLA + annual security review.",
    payment_terms: "annual_upfront",
    payment_terms_notes: null,
    pricing_model: "subscription",
    usage_commit_units: null,
    overage_rate: null,
    non_standard_clauses: JSON.stringify([
      "uptime_sla_99_9",
      "annual_security_review_at_no_cost",
    ]),
    ae_owner: "Priya Shankar",
    ae_manager: "Marcus Reilly",
    competitive_context:
      "Won against ZoomInfo Enterprise; price was within 5% but Clay's API/workflow capabilities sealed it.",
    customer_request:
      "Gong RevOps team led the eval. Standard enterprise structure with two non-standard clauses (SLA + security review). Closed in Q1 with quick legal turn.",
    close_date: "2026-02-14",
    is_scenario: 0,
  },
  {
    id: "deal_polymath_2026q1_new_logo",
    customer_id: "cust_polymath_robotics",
    name: "FY26 Enterprise New Logo",
    deal_type: "new_logo",
    stage: "closed_won",
    acv: 510_000,
    tcv: 1_530_000,
    term_months: 36,
    ramp_schedule_json: null,
    list_price: 580_000,
    proposed_price: 510_000,
    discount_pct: 12.1,
    discount_reason:
      "3-year commit (manufacturing/robotics). Expansion seat lock concession traded for term length.",
    payment_terms: "annual_upfront",
    payment_terms_notes: null,
    pricing_model: "subscription",
    usage_commit_units: null,
    overage_rate: null,
    non_standard_clauses: JSON.stringify([
      "expansion_seat_pricing_locked_18mo",
    ]),
    ae_owner: "Maya Chen",
    ae_manager: "Sarah Goldstein",
    competitive_context:
      "Defended against Apollo; won on integration depth into their custom MES.",
    customer_request:
      "Polymath's CRO signed in January. Standard enterprise structure with 18-month expansion seat lock.",
    close_date: "2026-01-22",
    is_scenario: 0,
  },
  {
    id: "deal_northstar_2025q4_new_logo",
    customer_id: "cust_northstar_defense",
    name: "Defense Vertical New Logo",
    deal_type: "new_logo",
    stage: "closed_won",
    acv: 480_000,
    tcv: 960_000,
    term_months: 24,
    ramp_schedule_json: null,
    list_price: 520_000,
    proposed_price: 480_000,
    discount_pct: 7.7,
    discount_reason:
      "Defense vertical. Compliance-heavy; minimal discount given subprocessor constraints accepted by customer.",
    payment_terms: "annual_upfront",
    payment_terms_notes: null,
    pricing_model: "subscription",
    usage_commit_units: null,
    overage_rate: null,
    non_standard_clauses: JSON.stringify([
      "fedramp_moderate_pending",
      "us_persons_only_subprocessor_addendum",
    ]),
    ae_owner: "Priya Shankar",
    ae_manager: "Marcus Reilly",
    competitive_context: "No active vendor competitor; replaced an internal tool.",
    customer_request:
      "Northstar requires US-persons-only for any subprocessor handling defense data. FedRAMP Moderate clause included pending our certification (target Q4 2026).",
    close_date: "2025-11-30",
    is_scenario: 0,
  },
  {
    id: "deal_kindred_2025q4_new_logo",
    customer_id: "cust_kindred_therapy",
    name: "Telehealth Mid-Market New Logo",
    deal_type: "new_logo",
    stage: "closed_won",
    acv: 145_000,
    tcv: 290_000,
    term_months: 24,
    ramp_schedule_json: null,
    list_price: 160_000,
    proposed_price: 145_000,
    discount_pct: 9.4,
    discount_reason:
      "Mid-market telehealth. Standard discount; PHI handling adds modest implementation overhead.",
    payment_terms: "annual_upfront",
    payment_terms_notes: null,
    pricing_model: "subscription",
    usage_commit_units: null,
    overage_rate: null,
    non_standard_clauses: JSON.stringify(["baa_executed_separately"]),
    ae_owner: "Devon Wright",
    ae_manager: "Sarah Goldstein",
    competitive_context: null,
    customer_request:
      "Kindred signed standard mid-market structure with separate BAA. Telehealth provider; PHI handling reviewed.",
    close_date: "2025-12-18",
    is_scenario: 0,
  },
  {
    id: "deal_quill_2026q1_new_logo",
    customer_id: "cust_quill_education",
    name: "Edtech Mid-Market New Logo",
    deal_type: "new_logo",
    stage: "closed_won",
    acv: 95_000,
    tcv: 190_000,
    term_months: 24,
    ramp_schedule_json: null,
    list_price: 105_000,
    proposed_price: 95_000,
    discount_pct: 9.5,
    discount_reason: "Standard mid-market edtech.",
    payment_terms: "annual_upfront",
    payment_terms_notes: null,
    pricing_model: "subscription",
    usage_commit_units: null,
    overage_rate: null,
    non_standard_clauses: null,
    ae_owner: "Devon Wright",
    ae_manager: "Sarah Goldstein",
    competitive_context: null,
    customer_request:
      "Quill closed standard mid-market structure. Ed-tech, light compliance footprint.",
    close_date: "2026-01-08",
    is_scenario: 0,
  },
  {
    id: "deal_beanstalk_2026q1_new_logo",
    customer_id: "cust_beanstalk_ai",
    name: "Seed-Stage AI Startup",
    deal_type: "new_logo",
    stage: "closed_won",
    acv: 32_000,
    tcv: 32_000,
    term_months: 12,
    ramp_schedule_json: null,
    list_price: 36_000,
    proposed_price: 32_000,
    discount_pct: 11.1,
    discount_reason: "Seed-stage startup; founder negotiated.",
    payment_terms: "annual_upfront",
    payment_terms_notes: null,
    pricing_model: "subscription",
    usage_commit_units: null,
    overage_rate: null,
    non_standard_clauses: null,
    ae_owner: "Jamal Okafor",
    ae_manager: "Marcus Reilly",
    competitive_context: null,
    customer_request:
      "Seed-stage AI startup. Standard plg-to-mid contract; founder negotiated discount.",
    close_date: "2026-03-04",
    is_scenario: 0,
  },
  {
    id: "deal_hightide_2026q1_new_logo",
    customer_id: "cust_hightide_devtools",
    name: "Devtools PLG-to-Small Conversion",
    deal_type: "new_logo",
    stage: "closed_won",
    acv: 28_000,
    tcv: 28_000,
    term_months: 12,
    ramp_schedule_json: null,
    list_price: 30_000,
    proposed_price: 28_000,
    discount_pct: 6.7,
    discount_reason: "Standard small-team annual.",
    payment_terms: "annual_upfront",
    payment_terms_notes: null,
    pricing_model: "subscription",
    usage_commit_units: null,
    overage_rate: null,
    non_standard_clauses: null,
    ae_owner: "Devon Wright",
    ae_manager: "Sarah Goldstein",
    competitive_context: null,
    customer_request:
      "Hightide upgraded from 4 self-serve seats. Standard small-team plan.",
    close_date: "2026-02-28",
    is_scenario: 0,
  },
  {
    id: "deal_sparrow_2026q2_new_logo",
    customer_id: "cust_sparrow_labs",
    name: "Sparrow Initial Annual",
    deal_type: "new_logo",
    stage: "closed_won",
    acv: 24_000,
    tcv: 24_000,
    term_months: 12,
    ramp_schedule_json: null,
    list_price: 24_000,
    proposed_price: 24_000,
    discount_pct: 0,
    discount_reason: null,
    payment_terms: "annual_upfront",
    payment_terms_notes: null,
    pricing_model: "subscription",
    usage_commit_units: null,
    overage_rate: null,
    non_standard_clauses: null,
    ae_owner: "Jamal Okafor",
    ae_manager: "Marcus Reilly",
    competitive_context: null,
    customer_request:
      "Standard small-team annual; no negotiation. Closed off the website self-serve flow with assistance.",
    close_date: "2026-04-12",
    is_scenario: 0,
  },
];

const closedLost: DealSeed[] = [
  {
    id: "deal_maquette_2026q1_lost_to_apollo",
    customer_id: "cust_maquette_studios",
    name: "Lost to Apollo on Price",
    deal_type: "new_logo",
    stage: "closed_lost",
    acv: 58_000,
    tcv: 116_000,
    term_months: 24,
    ramp_schedule_json: null,
    list_price: 65_000,
    proposed_price: 58_000,
    discount_pct: 10.8,
    discount_reason:
      "Final proposal at $58K; couldn't go lower without breaking floor (margin would have gone negative).",
    payment_terms: "annual_upfront",
    payment_terms_notes: null,
    pricing_model: "subscription",
    usage_commit_units: null,
    overage_rate: null,
    non_standard_clauses: null,
    ae_owner: "Devon Wright",
    ae_manager: "Sarah Goldstein",
    competitive_context:
      "Apollo offered $35K/yr; we couldn't get below $48K without breaking floor. Would have left margin negative.",
    customer_request:
      "Maquette went with Apollo at ~40% lower price. Their CFO blocked our quote citing budget freeze. Lost on price + procurement timing.",
    close_date: "2026-03-22",
    is_scenario: 0,
  },
  {
    id: "deal_coastline_2026q1_lost_procurement",
    customer_id: "cust_coastline_bank",
    name: "Lost to Procurement Delay",
    deal_type: "new_logo",
    stage: "closed_lost",
    acv: 185_000,
    tcv: 370_000,
    term_months: 24,
    ramp_schedule_json: null,
    list_price: 210_000,
    proposed_price: 185_000,
    discount_pct: 11.9,
    discount_reason: "Modest discount; lost to internal delay rather than vendor decision.",
    payment_terms: "annual_upfront",
    payment_terms_notes: null,
    pricing_model: "subscription",
    usage_commit_units: null,
    overage_rate: null,
    non_standard_clauses: JSON.stringify([
      "regulatory_audit_addendum_required",
    ]),
    ae_owner: "Maya Chen",
    ae_manager: "Sarah Goldstein",
    competitive_context: "No active competitor; lost to internal delay.",
    customer_request:
      "Coastline's regulatory audit window pushed procurement out 9 months. Champion left mid-cycle. Logged for re-engagement Q4 2026.",
    close_date: "2026-02-08",
    is_scenario: 0,
  },
  {
    id: "deal_rookery_2026q1_lost_price",
    customer_id: "cust_rookery_hr",
    name: "Lost to HR-Native Vendor",
    deal_type: "new_logo",
    stage: "closed_lost",
    acv: 42_000,
    tcv: 42_000,
    term_months: 12,
    ramp_schedule_json: null,
    list_price: 48_000,
    proposed_price: 42_000,
    discount_pct: 12.5,
    discount_reason: "Discounted to floor; CEO blocked on price.",
    payment_terms: "annual_upfront",
    payment_terms_notes: null,
    pricing_model: "subscription",
    usage_commit_units: null,
    overage_rate: null,
    non_standard_clauses: null,
    ae_owner: "Devon Wright",
    ae_manager: "Sarah Goldstein",
    competitive_context: "Lost to a smaller HR-tech-native vendor at $15K/yr.",
    customer_request:
      "Rookery went with a $15K/yr alternative. Champion liked us; CEO blocked on price.",
    close_date: "2026-01-30",
    is_scenario: 0,
  },
  {
    id: "deal_quokka_2025q4_lost_renewal",
    customer_id: "cust_quokka_travel",
    name: "Renewal Churn — Low Adoption",
    deal_type: "renewal",
    stage: "closed_lost",
    acv: 35_000,
    tcv: 35_000,
    term_months: 12,
    ramp_schedule_json: null,
    list_price: 35_000,
    proposed_price: 35_000,
    discount_pct: 0,
    discount_reason: null,
    payment_terms: "annual_upfront",
    payment_terms_notes: null,
    pricing_model: "subscription",
    usage_commit_units: null,
    overage_rate: null,
    non_standard_clauses: null,
    ae_owner: "Jamal Okafor",
    ae_manager: "Marcus Reilly",
    competitive_context: "No replacement vendor; reverted to internal sheet-based workflow.",
    customer_request:
      "Quokka's prior $35K contract churned at renewal — 47% feature adoption, never engaged with their CSM. Outreach for reactivation in Q1 went unanswered.",
    close_date: "2025-10-15",
    is_scenario: 0,
  },
  {
    id: "deal_halibut_2026q2_lost_scope",
    customer_id: "cust_halibut_marketplaces",
    name: "Lost on Custom Integration Scope",
    deal_type: "new_logo",
    stage: "closed_lost",
    acv: 36_000,
    tcv: 36_000,
    term_months: 12,
    ramp_schedule_json: null,
    list_price: 40_000,
    proposed_price: 36_000,
    discount_pct: 10.0,
    discount_reason: "Standard 10% discount; lost on services scope mismatch.",
    payment_terms: "annual_upfront",
    payment_terms_notes: null,
    pricing_model: "subscription",
    usage_commit_units: null,
    overage_rate: null,
    non_standard_clauses: null,
    ae_owner: "Jamal Okafor",
    ae_manager: "Marcus Reilly",
    competitive_context: "Lost to no decision (build in-house).",
    customer_request:
      "Halibut wanted custom integration into their proprietary marketplace API. Scope was 8 weeks of engineering — couldn't justify on contract size. Walked.",
    close_date: "2026-04-04",
    is_scenario: 0,
  },
];

export const additionalDeals: DealSeed[] = [
  ...negotiation,
  ...proposal,
  ...discovery,
  ...closedWon,
  ...closedLost,
];

export function seedAdditionalDeals(db: DB): number {
  const insert = db.prepare(`
    INSERT OR REPLACE INTO deals (
      id, customer_id, name, deal_type, stage, acv, tcv, term_months,
      ramp_schedule_json, list_price, proposed_price, discount_pct,
      discount_reason, payment_terms, payment_terms_notes, pricing_model,
      usage_commit_units, overage_rate, non_standard_clauses, ae_owner,
      ae_manager, competitive_context, customer_request, close_date,
      is_scenario
    ) VALUES (
      @id, @customer_id, @name, @deal_type, @stage, @acv, @tcv, @term_months,
      @ramp_schedule_json, @list_price, @proposed_price, @discount_pct,
      @discount_reason, @payment_terms, @payment_terms_notes, @pricing_model,
      @usage_commit_units, @overage_rate, @non_standard_clauses, @ae_owner,
      @ae_manager, @competitive_context, @customer_request, @close_date,
      @is_scenario
    )
  `);

  const tx = db.transaction((rows: DealSeed[]) => {
    for (const row of rows) insert.run(row);
  });
  tx(additionalDeals);
  return additionalDeals.length;
}
