import type { Workbook } from "exceljs";
import type { ArtifactInput } from "../types";
import {
  addTitleRow,
  FMT_MONEY_WHOLE,
  FMT_NUM,
  FMT_PCT,
  setColumnWidths,
  styleBody,
  styleLabel,
  styleMono,
} from "./styles";

// Tab 1 — Deal Summary. Static metadata block. No formulas; this tab is the
// orientation surface — everything else references real fields.

export function buildDealSummaryTab(
  workbook: Workbook,
  input: ArtifactInput,
  tabName: string,
): void {
  const ws = workbook.addWorksheet(tabName);
  setColumnWidths(ws, [28, 36]);

  let row = addTitleRow(
    ws,
    "Deal Summary",
    `${input.deal.customer.name} — ${input.deal.name}`,
  );

  const { deal } = input;

  // Body laid out as label / value pairs in columns A / B. Numeric values
  // get explicit number formats so they read cleanly on open.
  const rows: Array<{
    label: string;
    value: string | number;
    fmt?: string;
    mono?: boolean;
  }> = [
    { label: "Customer", value: deal.customer.name },
    { label: "Customer segment", value: formatSegment(deal.customer.segment) },
    { label: "Industry", value: deal.customer.industry },
    { label: "Headcount", value: deal.customer.employee_count, fmt: FMT_NUM },
    { label: "Deal type", value: titleCase(deal.deal_type.replace(/_/g, " ")) },
    { label: "Deal stage", value: titleCase(deal.stage.replace(/_/g, " ")) },
    { label: "AE owner", value: deal.ae_owner },
    { label: "AE manager", value: deal.ae_manager },
    { label: "ACV (proposed)", value: deal.acv, fmt: FMT_MONEY_WHOLE },
    { label: "TCV (proposed)", value: deal.tcv, fmt: FMT_MONEY_WHOLE },
    { label: "Term length (months)", value: deal.term_months, fmt: FMT_NUM },
    { label: "Discount % (headline)", value: deal.discount_pct / 100, fmt: FMT_PCT },
    { label: "Pricing model", value: titleCase(deal.pricing_model.replace(/_/g, " ")) },
    { label: "Payment terms", value: deal.payment_terms.replace(/_/g, " ") },
    { label: "Generated at", value: input.generatedAt.toISOString() },
    {
      label: "Generated by",
      value: `Kiln · ${input.appUrl}`,
      mono: true,
    },
    { label: "Review ID", value: input.reviewId, mono: true },
  ];

  for (const r of rows) {
    const lbl = ws.getCell(row, 1);
    const val = ws.getCell(row, 2);
    lbl.value = r.label;
    styleLabel(lbl);
    val.value = r.value;
    if (r.mono) {
      styleMono(val);
    } else {
      styleBody(val);
    }
    if (r.fmt) val.numFmt = r.fmt;
    row++;
  }

  // Synthesis paragraph below the metadata. Wraps for legibility.
  row += 1;
  const synthesisLabel = ws.getCell(row, 1);
  synthesisLabel.value = "Executive synthesis";
  styleLabel(synthesisLabel);
  row++;
  const synthesisCell = ws.getCell(row, 1);
  synthesisCell.value = input.synthesis;
  synthesisCell.font = { name: "Calibri", size: 10, italic: true };
  synthesisCell.alignment = { wrapText: true, vertical: "top" };
  ws.mergeCells(row, 1, row, 2);
  ws.getRow(row).height = Math.min(180, Math.max(60, input.synthesis.length / 5));
}

function titleCase(s: string): string {
  return s
    .split(/\s+/)
    .map((w) => (w.length > 0 ? w[0].toUpperCase() + w.slice(1).toLowerCase() : w))
    .join(" ");
}

function formatSegment(s: string): string {
  if (s === "plg_self_serve") return "PLG / Self-serve";
  return titleCase(s.replace(/_/g, " "));
}
